name: mgc_predictor
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8,<3.12
  - pandas>=1.5.0
  - numpy>=1.23.0
  - scipy>=1.9.0
  - biopython>=1.79
  - xgboost>=1.7.0
  - scikit-learn>=1.1.0
  - joblib>=1.2.0
  - blast>=2.13.0  # NCBI BLAST+ for KEGG annotation (from bioconda)

